### ISSUE TITLE
not using default options let defaultOptions = {... 

### ISSUE THREAD

**Issue by freerider7777** [ankane/chartkick.js#101]
Hi,
Why are you overriding default options? Such as drawOnChartArea, maxTicksLimit and others.
I had to inspect the sources to find out why the default behavior of pure chart.js and chartckick are not the same...
(Using vue-chartkick I had to inspect both)...

**Comment by ankane** [comment]
Chartkick has it's own style - is this a question or a complaint?

**Comment by freerider7777** [comment]
It can be found only in code
Complaint, it would be nice if native styles were available for seamless upgrade to vue-chartkick (from pure chart.js)

**Comment by ankane** [comment]
Gotcha
