### ISSUE TITLE
[Idea] Add support to Google Materials Charts

### ISSUE THREAD

**Issue by marcoborsoi** [ankane/chartkick.js#102]
Hey @ankane ,

First, congratulations for your work. I'm using the Vue version and it's awesome!

I was wondering if an option to support Google Material Charts could be added. It seems it's still in Beta, but since it's figuring it Google Charts official documentation, it would nice for those who wants to try it.

According to Google (see https://developers.google.com/chart/interactive/docs/gallery/columnchart):

> Creating a Material Column Chart is similar to creating what we'll now call a "Classic" Column Chart. You load the Google Visualization API (although with the 'bar' package instead of the 'corechart' package), define your datatable, and then create an object (but of class google.charts.Bar instead of google.visualization.ColumnChart).

> Since bar charts and column charts are essentially identical but for orientation, we call both Material Bar Charts, regardless of whether the bars are vertical (classically, a column chart) or horizontal (a bar chart). In Material, the only difference is in the bars option. When set to 'horizontal', the orientation will resemble the traditional Classic Bar Chart; otherwise, the bars will be vertical.

and

> The Material Charts are in beta. The appearance and interactivity are largely final, but many of the options available in Classic Charts are not yet available in them. You can find a list of options that are not yet supported in this issue. 

> Also, the way options are declared is not finalized, so if you are using any of the classic options, you must convert your to material options by replacing this line: 

> chart.draw(data, options);

> ...with this: 

> chart.draw(data, google.charts.Bar.convertOptions(options));

On the Google Charts official documentation you will find this example: https://jsfiddle.net/k3gwv7fs/

So, while the Classical Chart is drawn like this:

`var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
chart.draw(data, options);`

The Material Charts option would draw the chart like this:

`var chart = new google.charts.Bar(document.getElementById('chart_div'));
chart.draw(data, google.charts.Bar.convertOptions(options));`

and we have to add bars: 'horizontal' or 'vertical' to the options object for this example

Thanks!

All the best!

**Comment by ankane** [comment]
Cleaning up issues
