### ISSUE TITLE
Unable to set min and max of x axis.

### ISSUE THREAD

**Issue by ThinkSalat** [ankane/chartkick.js#103]
Hello,

I've searched the documentation and I don't see any way to set the min/max of the X Axis. I do know setting min and max works on the Y Axis.

For example, I want a scatter chart that shows the past 15 days on the x axis. Something so simple should be doable but I don't see anything in the documentation for this.

**Comment by ankane** [comment]
Hey @ThinkSalat, Chartkick doesn't have its own option for this, so you'll need to use the `library` option. Happy to look at a PR for `xmin` and `xmax` options.

**Comment by ankane** [comment]
Just needed this for one of my own projects, so added it for Chart.js. Still happy to accept a PR for other libraries.
