### ISSUE TITLE
[FAQ] How to use chartkick.js using webpack

### ISSUE THREAD

**Issue by kirantpatil** [ankane/chartkick.js#106]
Hi,

I have migrated to Rails 6 and it is not supporting javascript asset pipeline which is moved to webpacker.

How should I go about and create charts with rails since chartkick.js is pure javascript ? 

I would like to embed charts in ruby as below but without using `gem "chartkick"` and using `yarn add chartkick chart.js`

`<%= line_chart User.group_by_day(:created_at).count %>`

Thanks.

**Comment by ankane** [comment]
Hey @kirantpatil, the Ruby project has instructions in the readme.

**Comment by kirantpatil** [comment]
Hi, Can I use it with Rails 6 beta ?

**Comment by kirantpatil** [comment]
I had a doubt of it not work if we install using yarn.

I installed now using yarn and I could embed in erb as mentioned in example and it works great.
