### ISSUE TITLE
PROPOSAL dataTransform() to allow alternate data formats to be supported

### ISSUE THREAD

**Issue by drush** [ankane/chartkick.js#108]
Allow an optional transform callback in order to give the caller a chance to transform API response in the format Chartkick requires.  This would enable connectivity from a variety of other API standards such as JSONAPI, array of hashes, etc.  

These examples would accept raw data in the form:
```json
[
{ "date": "2018-01-01", "value": 16 },
{ "date": "2019-01-01", "value": 20 },
]
```

Javascript
```javascript
new Chartkick.LineChart(
  "chart-1", 
  "/stocks", 
  (rawResponse) => rawResponse.map(row => [row.date, row.value])
)
```

React:
```javascript
<LineChart data='/stocks' dataTransform={(rawResponse) => rawResponse.map((row) => [row.date, row.value]) } />
```

@ankane

**Comment by ankane** [comment]
Hey @drush, sorry for the delay. Just merged #116, which I think is more flexible.
