### ISSUE TITLE
[Idea] Give the ability to zoom for large amounts of data

### ISSUE THREAD

**Issue by DrySoldier** [ankane/chartkick.js#109]
Hi,

I currently use chartkick.js to parse a lot of data with a scatterplot, to plot messages over time. Is there anyway to zoom in so you can see where the specific points are, instead of looking at one big blob of points?

**Comment by ankane** [comment]
Hey @DrySoldier, sorry for the delay. There isn't a way to zoom as far as I know. You'll probably want to use a charting library directly.
