### ISSUE TITLE
How can i use a multilines labels in yAxis ? 

### ISSUE THREAD

**Issue by alphabet2061** [ankane/chartkick.js#110]
Hi,
https://image.noelshack.com/fichiers/2019/21/6/1558770347-capture.png
with vueJs, I want to read this whole question of 400 characters. if I write a line break \ n or <br> it's written as a text and not written as a code

**Comment by ankane** [comment]
Hey @alphabet2061, it looks likes newlines are only preserved with Google Charts right now (just show up as spaces with other libraries). Happy to accept a PR for other charting libraries. It looks like it's possible for at least Chart.js:  https://github.com/chartjs/Chart.js/blob/master/samples/scales/multiline-labels.html

**Comment by ankane** [comment]
Cleaning up issues
