### ISSUE TITLE
[Idea] Custom Markers for Highcharts LineChart

### ISSUE THREAD

**Issue by pulgaroja** [ankane/chartkick.js#115]
Hello @ankane,

First of all thank you so much for this amazing project and all the hard work you have put into it. It's been of great help for my projects! I was just wondering if you would consider the following small change:

**file: src/adapters/highcharts.js**
line 166: `series[i].marker = {symbol: "circle"};`

to

line 166: `series[i].marker = series[i].marker || {symbol: "circle"};`

to allow for customized markers, at the moment any custom values set to **marker** is overwritten on this line to just `{symbol: "circle"}` and all other changes are lost.

I am using your wonderful `react-chartkick` and I believe this change would allow me to fully match my clients design.

Again, thank you for your time and consideration.

**Comment by ankane** [comment]
Hey @pulgaroja, thanks for the suggestion. I'd like to make it easier to customize series, but want to keep the Chartkick options separate from the underlying charting library options. One idea is to add support for the `dataset` option to accomplish this like with Chart.js (see the readme for how it works). Happy to review a PR for it.
