### ISSUE TITLE
[Idea] Show loading after updateData(newData)

### ISSUE THREAD

**Issue by diesl** [ankane/chartkick.js#119]
Hi,

I use a Chart with an own endpoint, and initially it displays "_Loading..._" until the Chart has been rendered. On my page, I sometimes switch to another endpoint by using `updateData(newEndpoint)`.

Now my question/idea:
* How to display "_Loading..._" during this second rendering? (Backend chart data generation may take a while). This would be a nice feature because now the chart seems stuck until the data has been received.
* Is there a way to translate the "_Loading..._" string?

**Comment by ankane** [comment]
Hey @diesl, thanks for the suggestions! Added these to the plan for Chartkick 4. For now, instead of calling `updateData`, you can destroy the chart, show the loading message, and recreate it to accomplish this.

**Comment by ankane** [comment]
Hey @diesl, just pushed Chartkick 4 with a `loading` option that should work for both those cases. Thanks again for the suggestion!

**Comment by diesl** [comment]
Thanks for the notice! I will take a look once we will update to the new version.
