### ISSUE TITLE
[Idea] Support for adding more columns to the Google Timeline

### ISSUE THREAD

**Issue by nicknezis** [ankane/chartkick.js#121]
I would like to use the Google Timeline, but the Chartkick use of it seems to be limiting the ability to set additional columns.

[This code](https://github.com/ankane/chartkick.js/blob/102455c16550c6ff11d67ef35cca1d1b98af2e2e/chartkick.js#L742) shows that only 3 columns are supported. Is there perhaps some suggestion of how I can accomplish what I want with Chartkick? If not, could I contribute back a feature to support optional additional columns? 

This limitation was mentioned on [StackOverflow](https://stackoverflow.com/a/36682483/118999).

**Comment by ankane** [comment]
Hey @nicknezis, thanks for the suggestion and interest in contributing. Unfortunately, there's not a way to pass additional columns and it's not a feature I'd like to support right now, but you could fork the project and update it for your app. Here's where the Google Charts data table is constructed: https://github.com/ankane/chartkick.js/blob/133ace545ef26168ec2b2c250677a6447b38069e/src/adapters/google.js#L266-L270

**Comment by ankane** [comment]
Cleaning up issues
