### ISSUE TITLE
setLabelSize always trims labels making it impossible to see dates on X axis

### ISSUE THREAD

**Issue by Ibiza385** [ankane/chartkick.js#124]
I'm using vue-chartkick which wraps this
https://github.com/ankane/chartkick.js/blob/master/src/adapters/chartjs.js

Dates on X axis gets trimmed so it is not possible to see whole date. Part always gets replaced by three dots. There is only 7 characters visible and three dots. I'm testing on big screen.
I'm backend developer, not JS, but I assume 
let maxLabelSize = Math.ceil(chart.element.offsetWidth / 4.0 / data.labels.length);
is wrong because data.labels.length counts how many dates are there in array, not label text length. So if I put 10 dates it will not trim labels, but If I have 60 dates, it trims them with out any need for that and making graph unusable.

**Comment by ankane** [comment]
Hey @Ibiza385, can you share a minimal example to reproduce? (either Vue or JS)
