### ISSUE TITLE
Examples broken: "Geo Chart" and "Markers"

### ISSUE THREAD

**Issue by drnic** [ankane/chartkick.js#125]
https://ankane.github.io/chartkick.js/examples/

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/108/108149376-70c75000-711e-11eb-99fb-5028852c3c77.png">

Tested on MacOS 11 Firefox + Safari

Error looks to be:

<img width="829" alt="image" src="https://user-images.githubusercontent.com/108/108149453-9d7b6780-711e-11eb-82c8-97b0070bbc9c.png">

```
Unhandled Promise Rejection: TypeError: undefined is not a constructor (evaluating 'new this.library.visualization[type](chart.element)')
```

**Comment by ankane** [comment]
Thanks @drnic, the Geo Chart should be fixed, and I've removed Markers since it now requires an API key.
