### ISSUE TITLE
Help to use chartkick/chart.js in Rails 6 project 

### ISSUE THREAD

**Issue by neuberfran** [ankane/chartkick.js#127]
Hi,

I stay transpose this project https://www.creativebloq.com/html5/code-real-time-survey-html5-websockets-12116562 to Rails 6 and I have issue with charts. I need your help (Based on the files I'm making available) to include charts or chartkick.js in my project. 

You can command CTRL-F and "jQuery chart plug-in" in the article to find the shape it was using the charts.

I would like you to help integrate the project below into my project and resolve the issue of the photo:
[GitHub](https://chartkick.com/)

![GitHub Logo](/images/logo.png)
Format: ![Alt Text](https://user-images.githubusercontent.com/38701397/114950770-26b2d000-9e2a-11eb-9366-cb097d26ea2f.png)

[GitHub](https://github.com/neuberfran/realtime_survey/blob/main/app/javascript/packs/application.js) 

[GitHub](https://github.com/neuberfran/realtime_survey/blob/main/app/views/survey_entries/index.html.erb)

**Comment by ankane** [comment]
Hey @neuberfran, check out the Contributing Guide for where to get help. If you've found a bug, please use the gist to recreate the issue.
