### ISSUE TITLE
Chartkick forces pointFormatter option in Highcharts

### ISSUE THREAD

**Issue by Goamaral** [ankane/chartkick.js#128]
**Describe the bug**
I am trying to use Highchart's [tooltip.pointFormat option](https://api.highcharts.com/highcharts/tooltip.pointFormat) but this option is ignored because Chartkick defines a tooltip.pointFormatter at [/src/adapters/highcharts.js](https://github.com/ankane/chartkick.js/blob/master/src/adapters/highcharts.js#L114)

This causes Highcharts to use the tooltip.pointFormatter instead of using the tooltip.pointFormat

**To reproduce**
Use this code to reproduce:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <script src="https://unpkg.com/chartkick"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
  </head>
  <body>
    <div id="sales_evolution_chart" style="height: 300px;"></div>
    <script>
      new Chartkick.AreaChart(
      	"sales_evolution_chart",
        [["2021-05-14",0],["2021-05-15",0],["2021-05-16",0],["2021-05-17",16],["2021-05-18",1]],
        {
          "library": {
            "tooltip": {
              "useHTML":true,
              "borderWidth":1,
              "padding":0,
              "style": {"color":"black"},
              "pointFormat":"\u003cdiv class=\"chart_tooltip__body chart_tooltip__body--centered\"\u003e{point.y} Bilhetes Vendidos\u003c/div\u003e","xDateFormat":"\u003cdiv\u003e%e %b %Y\u003c/div\u003e",
              "headerFormat":"\u003cdiv style=\"background-color: {series.color};\" class=\"chart_tooltip__header\"\u003e{point.key}\u003c/div\u003e",
              "shared":false
            }
          }
        }
      )
    </script>
  </body>
</html>
```

**Comment by ankane** [comment]
Hey @Goamaral, thanks for reporting. Fixed in the commit above.

**Comment by Goamaral** [comment]
When will 4.0.5 be released?
Tried to add `"chartkick": "ankane/chartkick.js#master"` in my _package.json_ but _chartkick/highcharts/highcharts.esm.js_ breaks.
It is not able to find chartkick `import Chartkick from "chartkick"`
