### ISSUE TITLE
Metric name on geocharts

### ISSUE THREAD

**Issue by ptdev** [ankane/chartkick.js#16]
It would be nice to be able to use a similar format than the one used for multiple axes on the geochart option so we could name the metric accordingly.
For example, instead of using:

```
new Chartkick.GeoChart("chart-1", [["United States",44],["Germany",23],["Brazil",22]]);
```

we would also be able to use something like:

```
var data = {"name":"Views", "data":[["United States",44],["Germany",23],["Brazil",22]]};
new Chartkick.GeoChart("chart-1", data);
```

The tooltips when hovering countries would then show "Views: X" instead of the hardcoded "Value: X"

Just a suggestion. Thanks for the great job on this lib.

**Comment by ankane** [comment]
Hey @ptdev, you can now use the `label` option for this.
