### ISSUE TITLE
Morrisjs support

### ISSUE THREAD

**Issue by mieko** [ankane/chartkick.js#2]
I'm working on an application that is currently using [Morris.js](http://www.oesmith.co.uk/morris.js/), which has some peculiar advantages over Google Charts and Highcharts in my weird, locked-down intranet environment:
- Free
- Can be served locally as a single .js file

I'd like to add a Morris.js backend to chartkick.js, so in the future I can just `gem` away on groupdate and chartkick.  My questions are:
1. Would the added size of supporting this charting library be appropriate for upstream?  And if so, 
2. What would your thoughts be on structuring for this and future backends, assuming that an additional `'Morris' in window` in a big if would start to seem iffy.

Regards.

**Comment by ankane** [comment]
Chartkick now supports an open source library (Chart.js), so going to close this.
