### ISSUE TITLE
Moving the legend to the top/bottom

### ISSUE THREAD

**Issue by esbm** [ankane/chartkick.js#22]
I've implemented these charts into a landing page https://www.npd.com/perspectives/topline-top-three/ and they work great. Only issue is that the legends get bunched up and sometimes cut off. Is there an option/way to move the legend to the top or bottom of the chart? Or maybe control the width of the chart itself in comparison to the legend?

Thanks,
Elliot

**Comment by ankane** [comment]
Created #73 for this.
