### ISSUE TITLE
Google vis, Specify Start and End as date

### ISSUE THREAD

**Issue by jchatel** [ankane/chartkick.js#23]
Hi all,

First, awesome library, loving it. Thumb up for simplicity.

Second, I'm using multiple date charts and would like to align them, so I need to specify a start and end date on the horizontal axis

Like this: http://jsfiddle.net/REgJu/

 new google.visualization.LineChart(
          document.getElementById('visualization')).
        draw(data, {width: 500, height: 400,
                    interpolateNulls: true,
                    min: 0,
                    max: 10,
                    hAxis: {
                        format: "MMM dd",
                        title: "Date", 
                        viewWindowMode: 'Explicit',
                        viewWindow:{
                            min: new Date(2012, 1, 13),
                            max: new Date(2012, 1, 19)
                            }
                        }
                    });

I'm trying this but I can't manage to make it work no matter what I try.

I have "undefined is not a function×" error.

line_chart @events.group_by_day(:created_at).count, library: {"hAxis" => {format: "MMM dd", title: "Responses date", viewWindowMode: "Explicit", viewWindow: {min: "new Date(2011, 1, 13)"}}}

Not sure how to make it work, any help appreciated

**Comment by ankane** [comment]
Cleaning up issues
