### ISSUE TITLE
Different x coordinates for multi-line series causes rendering error

### ISSUE THREAD

**Issue by benrudolph** [ankane/chartkick.js#25]
When I try and chart a multi-line series using dates as the x axis, but the two lines use different dates, I get a funky result. Here is the code:

``` javascript


var data = [
    {
      name: 'Messages Sent',
      data: {
        "2014-04-25 00:00:00 -0800": 1651,
        "2014-05-02 00:00:00 -0800": 264,
        "2014-05-09 00:00:00 -0800": 0,
        "2014-05-16 00:00:00 -0800": 773,
        "2014-05-23 00:00:00 -0800": 23,
        "2014-05-30 00:00:00 -0800": 81,
        "2014-06-06 00:00:00 -0800": 0,
        "2014-06-20 00:00:00 -0800": 34,
        "2014-07-03 00:00:00 -0800": 19,
      }
    },
   {
      name: 'Messages Sent 2',
      data: {
        "2014-05-15 00:00:00 -0800": 689,
        "2014-05-30 00:00:00 -0800": 680,
        "2014-06-13 00:00:00 -0800": 672,
        "2014-06-28 00:00:00 -0800": 671,
        "2014-07-11 00:00:00 -0800": 106,
        "2014-07-31 00:00:00 -0800": 741,
      }
    },
]
new Chartkick.LineChart("messages", data)

```

![screen shot 2014-08-08 at 6 10 33 pm](https://cloud.githubusercontent.com/assets/918514/3859268/9233c77a-1f16-11e4-82ab-0c61bdd61628.png)

**Comment by filipe-maia** [comment]
I'm also having a problem with highcharts.js (as sugested, I'm using `library: {interpolateNulls: true}`).

In the controller I have:
`@a = []`
`@a.push({"name" => "a1", "data" => [[10,2],[20,3],[25,1]]})`
`@a.push({"name" => "a2", "data" => [[5,3],[10,4],[20,2]]})`

And in the view I have:
`<%= line_chart @a.map{|a|`
`{name: a["name"], data: a["data"]}`
`}, discrete: true, library: {interpolateNulls: true} %>`

The chart that I get is in the attached image.
![charts error](https://cloud.githubusercontent.com/assets/9107130/10887762/abb29b7c-8180-11e5-9891-da894e32658f.png)

Am I doing something wrong?

**Comment by ankane** [comment]
@filipe-maia I'm not sure the option works with `discrete: true`.

**Comment by Peddz24** [comment]
Any fixes right now?
Having the same issue.

**Comment by ankane** [comment]
Cleaning up issues
