### ISSUE TITLE
Support for C3.js

### ISSUE THREAD

**Issue by ankane** [ankane/chartkick.js#28]
Looks promising https://github.com/masayuki0812/c3

**Comment by printercu** [comment]
+1 :)

**Comment by sman591** [comment]
+1, would be super cool to be able to update/reload data in set intervals with this

**Comment by printercu** [comment]
@ankane i can help with the task. wdyt about moving code to coffee-script or you like to keep it in js?
i also think that it's a good idea to extract adapters into separate files.

**Comment by ankane** [comment]
@printercu I've tried both C3 and Chart.js.  Both have advantages, and I'd really like to go with an open source charting option for Chartkick 2.0, but at the moment, neither supported everything required for Chartkick.

**Comment by ankane** [comment]
[C3](https://github.com/ankane/chartkick.js/tree/c3) and [Chart.js](https://github.com/ankane/chartkick.js/tree/chartjs) branches

**Comment by ankane** [comment]
Chartkick now supports an open source library (Chart.js), so going to close this.
