### ISSUE TITLE
Normal area/line charts instead of spline

### ISSUE THREAD

**Issue by cheerfulstoic** [ankane/chartkick.js#30]
Is it currently possible to do this?  I looked at the source code and it seemed to be hard coded.

**Comment by caseypugh** [comment]
@cheerfulstoic were you able to figure this out? I'm having the same issue. The `areaspline` and `spline` are hardcoded and don't seem to be overridable.

**Comment by cheerfulstoic** [comment]
I wasn't able to figure it out, sorry.  It seemed to be hardcoded to me too.  Unfortunately I moved on from the project where this was needed.  @brettskiii was the one whom I was working with, so he might be able to comment

**Comment by brettskiii** [comment]
Yes ended up doing my own stuff here didn't find a solution

**Comment by aqabawe** [comment]
@cheerfulstoic hey, I'm using chartkick to plot line charts, removing `|| "spline"` from https://github.com/ankane/chartkick.js/blob/master/chartkick.js#L315 removes the spline and the chart plots with straight lines. Don't know how does this affect other charts though.

**Comment by ankane** [comment]
With the latest version, you can now use the `{curve: false}` option.
