### ISSUE TITLE
[BUG] Error Loading Chart: No adapter found

### ISSUE THREAD

**Issue by CDevCom** [ankane/chartkick.js#31]
Hi,
i'm here to submit you a bug in chartkick , even if we're using google jsapi in our page , and then implemented it in order to use google charts , chartkick is showing this message anyway : "Error Loading Chart: No adapter found".
Even your live demo at : https://ankane.github.io/chartkick.js/examples/ has that bug.

Best regards,
CDevCom.

**Comment by ankane** [comment]
Cleaning up issues
