### ISSUE TITLE
Data series doesn't support keyed values (name, id, etc)

### ISSUE THREAD

**Issue by thepacketgeek** [ankane/chartkick.js#33]
Highcharts supports series objects with keyed values for name, id, etc.. But chartkick.js does not.

For example, this works with chartkick in a series:
    `'data': {'2014-11-01': 98, '2014-11-14': 98}`

But trying to use the data attributes specified [here](http://api.highcharts.com/highcharts#series.data) like this..
`'data': [{'name': 'test1', 'x': '2014-11-1', 'y': 98},{'name': 'test2', 'x': '2014-11-12', 'y': 98}]`
... gives an error:
`TypeError: undefined is not an object (evaluating 'n.replace')`

in the `fetchDataSource() function` (line 172 of chartkick.js)

Supporting arrays of data objects along with the key, value pairs would be very helpful because tooltips can be populated with the 'name' value instead of default x,y coordinates.

**Comment by ankane** [comment]
Cleaning up issues. For future readers, you'll need to use the Chartkick format. You can use Highcharts directly if you want to use the Highcharts format.
