### ISSUE TITLE
Multiple Options

### ISSUE THREAD

**Issue by esbm** [ankane/chartkick.js#36]
Is there a way to use multiple options? For example, I'm creating a Discreet Line Chart with these options:

{"colors": ["#00a1de", "#f0ab00", "#9c0"]}, {"discrete": true}, {"min": 150});

The problem is, it only takes the first option (which is "colors" in this case) and ignores the remaining. Is there a way get all of them to work? If so, am I doing it incorrectly?

Thanks for your help.

**Comment by ankane** [comment]
So close.

```js
{"colors": ["#00a1de", "#f0ab00", "#9c0"], "discrete": true, "min": 150});
```

**Comment by esbm** [comment]
Ahhh, much appreciated.
