### ISSUE TITLE
Customizable GeoChart labels

### ISSUE THREAD

**Issue by mdiebolt** [ankane/chartkick.js#37]
Right now, GeoChart will only show "Value" as a label. http://monosnap.com/image/qj8RVYdAkBNtqSBd8CyOZGLBA2wpJr.png

Would you be open to a PR making this behavior parametrizable via an option passed into the GeoChart method?

**Comment by buren** [comment]
@mdiebolt see referensed PR. 

_Shameless self promote_: If your looking for support for more charts, options and auto-refresh feature you can check out my fork https://github.com/buren/chartkick.js, which has most of the open PRs in this repo merged..
