### ISSUE TITLE
html entity

### ISSUE THREAD

**Issue by andriusvs** [ankane/chartkick.js#55]
Hello,
i tried this - "m& # 279;n" ( i made space here to prevent this form convert entity ) and got the same as written :), must be - mėn. So my language and russian language fail, i have huge convertion table and want to use it . I really don't understand this - <   script    > var Chartkick = {  "language": "de   "};</     script    >
i add this, mark language "lt", but it not working.
I found another language issue. See attached file. English is good :), but how about another language.
![lang error](https://cloud.githubusercontent.com/assets/9377308/10507644/8d2a7c2e-732a-11e5-80c4-817f86dcbd12.png)

Unable to add  unit of measurement in table.
Thanks, my email andrius.vs@gmail.com if u need it.

**Comment by ankane** [comment]
Hey @andriusvs, I'm having trouble following. Can you paste some code examples and explain more?

**Comment by andriusvs** [comment]
Hello, sorry i was busy. 
My answer/question in image.
![question 2](https://user-images.githubusercontent.com/9377308/32594247-f2701f32-c533-11e7-83de-be3ec9a77965.png)
