### ISSUE TITLE
Implement box chart / candlestick chart

### ISSUE THREAD

**Issue by rajsahae** [ankane/chartkick.js#60]
Originally posted here: https://github.com/ankane/chartkick/issues/241
but this seems to be the more appropriate place to make the request.

Google Candlestick Charts (aka Highcharts Box Plot) isn't implemented. Would be really nice to have.

**Comment by ankane** [comment]
Hey @rajsahae, thanks for the request, and sorry for the long delay. There are no plans to support additional chart types at the moment.
