### ISSUE TITLE
Is it possible to link to an url when click on the chart ?

### ISSUE THREAD

**Issue by rafaeljneves** [ankane/chartkick.js#63]
Hello, 

Thank you for this tool! it's amazing! 
I'm newbie in rails / chartkick.

I'm currently using pie charts, and I'm wondering if there is a way I can get each section of my pie chart to navigate to an url.

I would like to know if it is possible / there is a way to , on clicking on the graph, it open an url link ? So if is there a way let me know. thanks!!!

``` javascript
    <h1>Pie Chart</h1>
    <div id="chart-2" style="height: 300px;"></div>
    <script>
      new Chartkick.PieChart("chart-2", [["Blueberry",44, "http://link1.com"],
                                                             ["Strawberry",23, "http://link2.com"],
                                                             ["Banana",22, "http://link3.com"],
                                                             ["Apple",21, "http://link4.com"],
                                                             ["Grape",13, "http://link5.com"]]);
    </script>
```

**Comment by kwent** [comment]
Hi @rafaeljneves,

Right now the only way i found is below (only works with Google Chart adapter in this example)

```javascript
var chartWrapper = Chartkick.charts["chart-1"]
var chart = chartWrapper.chart
var data = chartWrapper.data
google.visualization.events.addListener(chart, 'select', function() {
  selection = chart.getSelection()
  if(selection && selection[0]) {
    window.open(window.location.href + '?filter=' + data[selection[0].row][0], '_blank');
  }
});
```

This will open a new tab with an additional params `filter=label` of the selected portion of your pie. Not exactly what you requested but might help others.

Regards,

**Comment by rafaeljneves** [comment]
Hi. Thanks for feedback. Its good to know this piece of implementation.
Regards.
Em 2 de jun de 2016 7:59 PM, "Quentin Rousseau" <notifications@github.com>
escreveu:

**Comment by ankane** [comment]
Cleaning up issues

**Comment by guptamadhur** [comment]
The simple way of adding a link to google pie chart is to first select the specific selection of chart by:
     ```
google.visualization.events.addListener(chart, 'select', function() {
    var row = chart.getSelection()[0].row;
    window.open('http://www.google.com'); //This will open Google in a new window.
  });
```
`Full Example : https://jsfiddle.net/madhurgupta/bcpe3gks/6/`

**Comment by jlneto** [comment]
With this code

    google.visualization.events.addListener(chart, 'select', function() {

google.visualization throws an error since it is undefined.

    Uncaught TypeError: Cannot read property 'events' of undefined

Where do we get google.visualization from?

**Comment by rafaeljneves** [comment]
@jlneto , its a kind OFFTOPIC here because the issue on chartkick was closed by ankane.

but this error you are facing, first you have to load google charts lib on your template (html file): 
``` <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>```

you may have a look at examples on: [Google Charts](https://developers.google.com/chart/interactive/docs/quick_start).

A 'problem' on Google Charts, IMHO, is that you need to be online, internet connection to draw graphics.  Its not possible to use it offline. If its not a bad issue for you, good luck.

**Comment by mcrundo** [comment]
This issue being closed is one of the many reasons I'm looking for a better visualization library - bad repo admins are bad for the community.

**Comment by deepakmahakale** [comment]
@ankane can we please reopen this issue or create a new feature request for the same?

People might be able to contribute if there's an open feature request.

**Comment by Papipo** [comment]
> @ankane can we please reopen this issue or create a new feature request for the same?
> 

It seems we can't.

**Comment by ankane** [comment]
This issue was closed since I was under the impression kwent had given a solution to rafaeljneves question.

Chartkick.js itself doesn't provide any functionality for click events, but you can use the `library` option to pass any custom options, as well as [the API](https://github.com/ankane/chartkick.js#api) to get the underlying chart object and call any functions on it.
