### ISSUE TITLE
Beginner: data format question

### ISSUE THREAD

**Issue by remcoNL** [ankane/chartkick.js#69]
Hi All,

I'm quite new to Chartkick and the code examples work just fine. 

However I want to put data from a database in a line chart. I don not understand what the format of this data must be. 

If i just put it in an array the dates do not get displayed (but the name of the variable does). 
I also tried JSON.stringify on my variables, but it doesn't help (Error Loading Chart). 
I also tried to put the dates in a new Date().
I even used the moment() on the dates, just to make sure (-; 

Can you please provide me with a code example (or explanation) of how to turn this into a Chart?

```
var f = 19;
var e = "2016-02-10";
var g = 5;
var h = "2016-02-11";
```

Thanks

**Comment by ankane** [comment]
Hey @remcoNL, try to make the format match that of the examples. You shouldn't need to convert anything to dates or use moment. For a line chart, the data above would be:

```js
var data = {"2016-02-10": 19, "2016-02-11": 5};
```

Alternatively, you can use multiple arrays.

```js
var data = [["2016-02-10", 19], ["2016-02-11", 5]];
```

I'd use whichever format is easier to get your data into.

**Comment by remcoNL** [comment]
Thank you so much for your quick response. When i 'type out' the dates, it works fine. But i'm making some mistake when i do this:
```
var f = 19;
var e = "2016-02-10";
var g = 5;
var h = "2016-02-11";

var data = [[e,f][h,g]];

new Chartkick.LineChart("chart-1", data);
```

**Comment by remcoNL** [comment]
O no, it works!

**Comment by ankane** [comment]
Cleaning up issues
