### ISSUE TITLE
How to select fonts?

### ISSUE THREAD

**Issue by remcoNL** [ankane/chartkick.js#70]
Hi All,

Is there a way to select a certain font?  Maybe someone has a link to this? i cannot find it. 

Thanks

**Comment by ankane** [comment]
There isn't, but we could add a `font` option for this.

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest AND someone wants to add this, please reply and we can continue to discussion.

**Comment by ankane** [comment]
Great 👍
