### ISSUE TITLE
Add support for bubble charts

### ISSUE THREAD

**Issue by ankane** [ankane/chartkick.js#72]

**Comment by lettergram** [comment]
How would I go about calling this?

**Comment by ankane** [comment]
See `examples/index.html` for examples.

**Comment by lettergram** [comment]
There still seems to be an issue with this. I am up for trying to fix it, just wanted to make sure I wasn't doing something wrong.

Here is an image of the error I am receiving when I go to examples/index.html, am I missing something?

<img width="1280" alt="screen shot 2017-01-13 at 12 41 32 pm" src="https://cloud.githubusercontent.com/assets/1498748/21944978/afc3563c-d98d-11e6-94fa-8617ac34bcc3.png">

**Comment by ankane** [comment]
Looks like the examples page had an older version of Chartkick.js. It's fixed now. Thanks for letting me know.
