### ISSUE TITLE
Add support for currency and percentages

### ISSUE THREAD

**Issue by ankane** [ankane/chartkick.js#74]
A few possible designs

```javascript
{prefix: "$"}
{suffix: "%"}
```

**Comment by amingilani** [comment]
Also add support for commas in large numbers

**Comment by rept** [comment]
Indeed, other parameters should be decimal_symbol, thousand_separator.  Is there currently any way of doing this (with Chartjs) or none at all?

**Comment by rept** [comment]
Another one could be decimal_places which would solve this one too: https://github.com/ankane/chartkick/issues/301

**Comment by ankane** [comment]
This has landed on master for Chart.js, along with `delimiter` (thousands separator) and `separator` (decimal separator).

**Comment by rept** [comment]
@ankane that is some excellent news!  Will test as soon as this is released.  Thanks!

**Comment by ankane** [comment]
Just fyi, I changed the separator names to `thousands` and `decimal` to make it more clear and easier to spell.

**Comment by ankane** [comment]
Just released 2.3.0 🎉
