### ISSUE TITLE
Add support for 2nd y-axis

### ISSUE THREAD

**Issue by ankane** [ankane/chartkick.js#79]
Possible design (comments welcome)

```js
new Chartkick.LineChart(id, [{name: "Series 1", data: data1}, {name: "Series 2", data: data2, y2: true}])
```

To set min and max values

```js
new Chartkick.LineChart(id, series, y2: {min: 0, max: 1000})
```

**Comment by dmitry-saritasa** [comment]
That would be a nice thing to have

**Comment by danielbressan** [comment]
Was this completed? Could someone point to the documentation for it if so? Thanks!

**Comment by ankane** [comment]
Not added, just removed feature requests from the issue tracker.

**Comment by papeldeorigami** [comment]
Too bad it wasn't implemented. We had to give up of Chartkick because this feature was missing and the customer needed it. Unfortunately, we also don't have the time to implement it right now.

**Comment by excerlee** [comment]
> Too bad it wasn't implemented. We had to give up of Chartkick because this feature was missing and the customer needed it. Unfortunately, we also don't have the time to implement it right now.

May I ask what solution did you use to replace chartkick?

**Comment by duarme** [comment]
@excerlee I found this issue while trying to accomplish the same thing. I'm currently implementing this using Chart.js directly, see: https://www.chartjs.org/docs/latest/samples/line/multi-axis.html it's easy enough to do, but not as awesome as using Chartkick.  

Hello @ankane, is anyone planning on adding this feature to Chartkick? I wish my JS skills were good enough to attempt it myself 😅
