### ISSUE TITLE
2.2.2 gives error on scatter_chart

### ISSUE THREAD

**Issue by arni1981** [ankane/chartkick.js#81]
I updated chartkick via bower from 2.2.1 to 2.2.2 and now I get the error

> Type mismatch. Value 2016-06-26T12:30:00.000Z does not match type number in column index 0

My setup is chartkick in Gemfile set to 2.2.2 and I install the js file via bower, version 2.2.2.
This works perfectly with js file 2.2.1.

**Comment by ankane** [comment]
Hey @arni1981, thanks for reporting 👍  Scatter plots only support a numeric x-axis. A date/time axis wasn't intended to work in previous versions (but sounds like it did with Google Charts).

**Comment by arni1981** [comment]
I see, thanks for the explanation. Use your chartkick gem/js a lot, good work.

**Comment by arni1981** [comment]
Thanks for the explanation. But when I try to use only the year part of the date, I get the error

> Type mismatch. Value 2006 does not match type number in column index 0

This is the complete code
`new Chartkick.ScatterChart("#scores_line", [[2006,37],[2007,36],[2008,36],[2008,38],[2009,34],[2009,39],[2012,36],[2013,38],[2014,39],[2014,37],[2014,36],[2014,39],[2014,35],[2014,43],[2016,36]], {"library":{"lineWidth":1,"pointSize":5,"curveType":"function","legend":{"position":"none"},"vAxis":{"gridlines":{"color":"#ddd"},"baselineColor":"#aaa"},"hAxis":{"gridlines":{"color":"#ddd"},"textPosition":"none","baselineColor":"#aaa"},"trendlines":{"0":{"color":"#555","lineWidth":3,"opacity":0.3,"visibleInLegend":true,"pointSize":0}}},"discrete":true,"min":null});`

**Comment by ankane** [comment]
That sounds like a bug. Will take a look tonight.

**Comment by ankane** [comment]
This is due to `discrete: true`. Scatter charts don't support the `discrete` option.

**Comment by arni1981** [comment]
Thanks for the explanation. I guess it just accidentally worked with earlier versions.
Anyway, I use your gem/js a lot, good work!
