### ISSUE TITLE
GeoChart Not working

### ISSUE THREAD

**Issue by graingerkid** [ankane/chartkick.js#82]
GeoChart doesn't appear to be working.

I've used your exact example...

`                    <div id="chart-0"></div>
                    <script>
                      new Chartkick.GeoChart("chart-0", [["United States", 44], ["Germany", 23], ["Brazil", 22]])
                    </script>`

All the other charts are rendering correctly using the Google charts as a version. Anyone else having issues?

**Comment by ankane** [comment]
It appears to be working on the example page. https://ankane.github.io/chartkick.js/examples/

Just takes some time to load.
