### ISSUE TITLE
Message if there is no data?

### ISSUE THREAD

**Issue by adambedford** [ankane/chartkick.js#84]
Is there a way to specify a message to be rendered instead of an empty chart if there is no data?

**Comment by ankane** [comment]
Hey @adambedford, not at the moment. Someone asked the same question in the Chartkick repo, so there's at least one other person who is interested. Happy to accept a PR for it.

For reference: https://github.com/ankane/chartkick/issues/302

**Comment by sivagollapalli** [comment]
@ankane Added. Could you please check?
