### ISSUE TITLE
Add support for custom tooltips

### ISSUE THREAD

**Issue by ankane** [ankane/chartkick.js#86]
Since Chartkick (Ruby) doesn't support JavaScript functions, the best approach is probably a new data format that supports it.

```js
[{x: 1, y: 2, tooltip: "Custom"}, ...]
```

**Comment by YouenEtrillard** [comment]
Hi, I have one question regarding this thread.

I am using chartkick with vuejs and would like to customise the tooltips for donut piecharts (labels displayed for example).
I was able to customise some global options this way :
`Chart.defaults.global.tooltips.borderColor = 'rgba(0,0,0,1)';`

But obviously I will need to be able to go further to have fully customised tooltips.
I have tried different methods but being new to vuejs, chartkick and chartjs I'm not sure we can bypass chartkick while we wait for the feature to be implemented.

Is it just not possible at all at the moment ?

If needed, here is an exemple by chartjs of how it is done with chartjs : 
http://www.chartjs.org/samples/latest/tooltips/custom-pie.html

Thanks for your work,
Much appreciated !

**Comment by ankane** [comment]
Hey @YouenEtrillard, custom tooltips haven't been added yet. I'd recommend checking out https://github.com/apertureless/vue-chartjs

**Comment by YouenEtrillard** [comment]
@ankane Cool, I will look at that when I have the time.
Thanks !

**Comment by JeffersonFilho** [comment]
Would this help? https://github.com/ankane/chartkick.js/pull/95

**Comment by ankane** [comment]
Closing out feature ideas to clean up GitHub Issues
