### ISSUE TITLE
add support for stepped line charts

### ISSUE THREAD

**Issue by blairanderson** [ankane/chartkick.js#88]
http://www.chartjs.org/docs/latest/charts/line.html

>The following values are supported for steppedLine:
`false`: No Step Interpolation (default)
`true`: Step-before Interpolation (eq. 'before')
`'before'`: Step-before Interpolation
`'after'`: Step-after Interpolation
If the steppedLine value is set to anything other than false, lineTension will be ignored.

![screen shot 2017-06-29 at 11 06 43 am](https://user-images.githubusercontent.com/955736/27703067-119f8a64-5cbb-11e7-9320-94a2745c9ed6.png)

**Comment by ankane** [comment]
Hey @blairanderson, this should now be possible with the `dataset` option.
