### ISSUE TITLE
Bug in displaying timeline chart

### ISSUE THREAD

**Issue by S-hack** [ankane/chartkick.js#89]
I found a really strange bug where I receive a "Cannot read property 'v' of undefined" based on the dates that the user enters. The only difference between the two snippets below is that the second date - one starts in 2009 and the other in 2010. The dates don't conflict, but the first one produces the error but the second one does not. The same issue occurs even if I reverse the list of dates in both examples.

PRODUCES ERROR:
new Chartkick.Timeline("chart-1", [["test1","2016-05-01","2017-07-12"],["test2","2010-07-01","2014-09-01"]]);

WORKS CORRECTLY:
new Chartkick.Timeline("chart-1", [["test1","2016-05-01","2017-07-12"],["test2","2009-07-01","2014-09-01"]]);

It seems this bug has to do with some math function regarding scaling of the distance between the two date ranges. I'm using this through the ruby gem. However, I diagnosed this through the browser javascript console and it seems to be a javascript issue because the only difference between getting the error and not is the set of dates I choose.

**Comment by ankane** [comment]
Hey @S-hack, what browser are you using (including version)? Both example work correctly in the latest Chrome.

**Comment by S-hack** [comment]
I'm testing on the latest Chrome build on Windows 10. 
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by S-hack** [comment]
More information about this issue: it appears on my Android phone (latest Chrome browser), but only when I'm viewing the page in portrait mode. When I switch to landscape mode, the error goes away.

**Comment by ankane** [comment]
Hey @S-hack, my guess is it's a possible bug with Google Charts. I don't there's much Chartkick can do.
