### ISSUE TITLE
Update colors when updating data on existing chart

### ISSUE THREAD

**Issue by adambedford** [ankane/chartkick.js#92]
I came across this today and it does make sense given that data and colors are supplied independently to Chartkick, however I'm running into an issue where updating the data on an existing chart puts the data and colors out of sync.

Is there a way to update the color series on an existing chart?

**Comment by ankane** [comment]
There isn't, but sounds like a good idea. Happy to accept a PR to add a `color` option to multiple series format.

```js
[{name: "Sales", data: {}, color: "green"}]
```

**Comment by ankane** [comment]
Closing out feature requests to clean up GitHub Issues. If there is still interest AND someone wants to add this, please reply and we can continue to discussion.
