### ISSUE TITLE
[Idea] Multi-series Dates

### ISSUE THREAD

**Issue by graingerkid** [ankane/chartkick.js#94]
Hi, 

Would be great if there was an easy way to plot two-time series with different dates. I've not figured out a clear route to doing this.

**Comment by ankane** [comment]
Hey @graingerkid, you can do this already. The dates in multi-series line charts don't need to be the same.

**Comment by graingerkid** [comment]
Yea, but they don't overlap.

Say, I have 2 date ranges 1st - 3rd and 20th - 23rd these would be displayed at opposite ends of the chart and not overlapping (line chart).

At least, that's all I've been able to do. Am I missing something?

**Comment by graingerkid** [comment]
Sorry just read my first comment and realized I wasn't being clear. My bad

**Comment by graingerkid** [comment]
So as an example:

`<div id="comparison" style="height: 300px;"></div>`

`<script>
      new Chartkick.LineChart("comparison", [
          {name: "Series A", data: [["01 Jan",32],["02 Jan",46],["03 Jan",28],["04 Jan",21]]},
          {name: "Series B", data: [["04 Jan",22],["05 Jan",36],["06 Jan",38],["07 Jan",30]]}
          ],
          {"discrete": true});
    </script>`

![coparison](https://user-images.githubusercontent.com/3381276/37564181-7c09a100-2a88-11e8-9b80-0b1572ea7435.png)

For a comparison, I'd want them overlapping.

**Comment by graingerkid** [comment]
Here's an example using chart.js: https://jsfiddle.net/7L0fu4er/13/

**Comment by ankane** [comment]
Ah, I see. There's not a way to do it right now with Chartkick. It's an interesting idea, but feel like it's probably not common enough to warrant adding.

**Comment by PenelopeFudd** [comment]
Actually, it's used in business, showing the current month's data over last month's data.  Substitute year/hour/minute/etc as necessary.
