### ISSUE TITLE
Server rendering breaks due to implicit window check

### ISSUE THREAD

**Issue by mikehdt** [ankane/chartkick.js#96]
A project I'm working on currently has server-side rendering. Chartkick breaks when compiling for the server due to no `window` object being present. It's possible to address the test for this:

`let config = window.Chartkick || {};`
becomes something like
`let config = (typeof window !== 'undefined' && window.Chartkick) || {};`

I'd be happy to raise a PR if you feel this would be an acceptable change.

**Comment by ankane** [comment]
Hey @mikehdt, about to push a new release, so made the change you suggested. Thanks!
